*Define a 3-D Array in Numpy and print each and every item*

In [1]:
import numpy as np

In [3]:
arr_3d=np.array([[[3,4], [5, 7]], [[8, 9], [16, 32]],[[11,2],[22,44]]])
print(arr_3d)

[[[ 3  4]
  [ 5  7]]

 [[ 8  9]
  [16 32]]

 [[11  2]
  [22 44]]]


In [4]:
arr_3d.ndim

3